:bug: Bump Docker image version...
Because CI/CD on GitHub Actions fails with following error;

```
  #6 [2/3] RUN tlmgr update --self
  #6 2.354
  #6 2.354 tlmgr: Local TeX Live (2024) is older than remote repository (2025).
  #6 2.354 Cross release updates are only supported with
  #6 2.354   update-tlmgr-latest(.sh/.exe) --update
  #6 2.354 See https://tug.org/texlive/upgrade.html for details.
  #6 ERROR: process "/bin/sh -c tlmgr update --self" did not complete successfully: exit code: 1
  ------
   > [2/3] RUN tlmgr update --self:
  2.354
  2.354 tlmgr: Local TeX Live (2024) is older than remote repository (2025).
  2.354 Cross release updates are only supported with
  2.354   update-tlmgr-latest(.sh/.exe) --update
  2.354 See https://tug.org/texlive/upgrade.html for details.
  ------
  Dockerfile:2
  --------------------
     1 |     FROM pandoc/extra:3.1.13.0-alpine
     2 | >>> RUN tlmgr update --self
     3 |     RUN tlmgr install ragged2e datetime fmtcount
     4 |
  --------------------
  ERROR: failed to solve: process "/bin/sh -c tlmgr update --self" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1
```

Relevant links;

- https://github.com/S0AndS0/curriculum-vitae/actions/runs/14759521286/job/41436457720
- https://tug.org/texlive/upgrade.html